### PR TITLE
No more trailings space.

### PR DESCRIPTION
**Pull request by Psycojoker**
I've removed all of it!

### CODE REVIEW

**Comment by thgeorgiou** [comment]
I actually put these empty lines there to make the code easier to read. I have no problem with removing them, but I wonder why.

**Comment by Psycojoker** [comment]
```
I actually put these empty lines there to make the code easier to read.
```

I'm surprised, how does this help you?

In general trailing spaces are considered useless and inelegant. The pep8 recommend to avoid using it.

Feel free to reject this pull request if you consider this to be usefull for you.

**Comment by thgeorgiou** [comment]
After all I removed most of these lines and just added more comments. So I think it's fine right now.

**Comment by Psycojoker** [comment]
Oh, I think we missunderstood. I'm talking about trailing spaces, not empty lines. Trailing spaces are white spaces after the last visible character at the end of a line, they aren't empty lines.

Like, this line have a lot of trailing space (select it to see it)

**Comment by thgeorgiou** [comment]
Oh, these spaces. Yes, these are indeed completely useless. I am closing this request since it can be automatically merged any more and since I actually removed most of these myself. Though, thanks for the heads up, I will take care so the code doesn't fill with them again.

**Pull request closed without merging**
